# Generated by Django 3.1.6 on 2021-08-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210812_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='added_product_quantity',
            new_name='product_size_and_quantity',
        ),
    ]
