# Generated by Django 3.1.6 on 2021-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210812_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size_and_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='remaining_product_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
