# Generated by Django 3.1.6 on 2021-08-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210812_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='remaining_product_quantity',
            new_name='remaining_size_and_quantity',
        ),
    ]
