# Generated by Django 3.1.6 on 2021-08-12 09:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210812_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
