# Generated by Django 3.1.6 on 2021-08-17 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_pic_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variation', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
