# Generated by Django 3.1.6 on 2021-05-03 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210405_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branc_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_address', models.TextField(blank=True, null=True)),
                ('brand_country', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_state', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_city', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('product_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_size', models.CharField(blank=True, max_length=255, null=True)),
                ('product_color', models.CharField(blank=True, max_length=255, null=True)),
                ('product_material', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_product', to='accounts.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_edited', models.DateTimeField(blank=True, null=True)),
                ('store_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('shop_type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=255)),
                ('shop_description', models.TextField(blank=True, null=True)),
                ('shop_address', models.TextField(blank=True, null=True)),
                ('shop_country', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_state', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_city', models.CharField(blank=True, max_length=255, null=True)),
                ('shop_zip_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_product', to='accounts.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BrandInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('follower_count', models.IntegerField(default=0)),
                ('total_items_count', models.IntegerField(default=0)),
                ('items_sold_count', models.IntegerField(default=0)),
                ('monthly_earning', models.IntegerField(default=0)),
                ('shops_count', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_insight', to='accounts.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stores', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='brand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brands', to=settings.AUTH_USER_MODEL),
        ),
    ]
