# Generated by Django 3.1.6 on 2021-05-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210503_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_shop',
        ),
    ]
