# Generated by Django 3.1.6 on 2021-05-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210513_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brand',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
