# Generated by Django 3.1.6 on 2021-05-28 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_store_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='follower_count',
            field=models.ManyToManyField(blank=True, default=None, related_name='brand_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='follower_count',
            field=models.ManyToManyField(blank=True, default=None, related_name='store_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StoreFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('FOLLOW', 'FOLLOW'), ('UNFOLLOW', 'UNFOLLOW')], default='UNFOLLOW', max_length=20)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_store', to='accounts.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_follower_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BrandFollow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(choices=[('FOLLOW', 'FOLLOW'), ('UNFOLLOW', 'UNFOLLOW')], default='UNFOLLOW', max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_brand', to='accounts.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
