# Generated by Django 3.1.6 on 2021-05-31 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210531_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='follower_count',
            new_name='store_follower',
        ),
    ]
