# Generated by Django 3.1.6 on 2021-06-03 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210603_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_store',
        ),
    ]
