# Generated by Django 3.1.6 on 2021-06-10 12:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_product_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=colorfield.fields.ColorField(default='#FFFFFFFF', max_length=18),
        ),
    ]
