# Generated by Django 3.1.6 on 2021-06-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210610_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
