# Generated by Django 3.1.6 on 2021-06-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20210611_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='p_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
