# Generated by Django 3.1.6 on 2021-06-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('main_pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('main_pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('normal_pic_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('normal_pic_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('normal_pic_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='accounts.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
