# Generated by Django 3.1.6 on 2021-06-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sale_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_type',
            field=models.CharField(blank=True, choices=[('Value', 'Value'), ('Percentage', 'Percentage')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tag_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Activewears', 'Activewears'), ('Dresses', 'Dresses'), ('Jackets And Coats', 'Jackets And Coats'), ('Jumpsuits and Playsuits', 'Jumpsuits and Playsuits'), ('Knitwear', 'Knitwear'), ('Swimwear', 'Swimwear'), ('Tops', 'Tops'), ('Trouser', 'Trouser'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
    ]
