# Generated by Django 3.1.6 on 2021-06-30 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_checkout_city_country_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='shop_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_brand', to='accounts.brand'),
        ),
    ]
