# Generated by Django 3.1.6 on 2021-07-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_brand_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_for',
            field=models.CharField(blank=True, choices=[('WOMEN', 'WOMEN'), ('MEN', 'MEN'), ('BOTH', 'BOTH')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(blank=True, choices=[('Activewears', 'Activewears'), ('Dresses', 'Dresses'), ('Jackets And Coats', 'Jackets And Coats'), ('Jumpsuits and Playsuits', 'Jumpsuits and Playsuits'), ('Knitwear', 'Knitwear'), ('Swimwear', 'Swimwear'), ('Tops', 'Tops'), ('Trouser', 'Trouser'), ('Accessories', 'Accessories'), ('Clothing', 'Clothing'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
