# Generated by Django 3.1.6 on 2021-07-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
