# Generated by Django 3.1.6 on 2021-07-09 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210708_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='storeimage',
            name='created_at',
        ),
    ]
