# Generated by Django 3.1.6 on 2021-07-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210709_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='BrandStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('site_background', models.CharField(blank=True, max_length=30, null=True)),
                ('main_color', models.CharField(blank=True, max_length=30, null=True)),
                ('texts_color', models.CharField(blank=True, max_length=30, null=True)),
                ('background_color_2nd', models.CharField(blank=True, max_length=30, null=True)),
                ('top_nav_background', models.CharField(blank=True, max_length=30, null=True)),
                ('top_nav_texts', models.CharField(blank=True, max_length=30, null=True)),
                ('parallax_effect', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_style', to='accounts.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
