# Generated by Django 3.1.6 on 2021-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20210716_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whoweare',
            name='para_1',
            field=models.TextField(blank=True, default='It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters', null=True),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='para_2',
            field=models.TextField(blank=True, default='It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters', null=True),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='para_3',
            field=models.TextField(blank=True, default='It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters', null=True),
        ),
    ]
