# Generated by Django 3.1.6 on 2021-08-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20210728_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='first_main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='second_main_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
