# Generated by Django 3.1.6 on 2021-08-15 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20210806_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
