# Generated by Django 3.1.6 on 2021-08-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_brandcategory_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whoweare',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
