# Generated by Django 3.1.6 on 2021-08-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210812_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
