# Generated by Django 3.1.6 on 2021-08-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_cartproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='total_payable',
            field=models.FloatField(default=0),
        ),
    ]
