# Generated by Django 3.1.6 on 2021-08-20 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_cartproduct_total_payable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address',
        ),
    ]
